language: node_js
node_js:
- '8'
script:
- yarn build
deploy:
- provider: gcs
  access_key_id: GOOG3UJZKTUH2MM2KWGJ
  secret_access_key:
    secure: tT+pHOM050QGzjBUlDmfvf1pPbbpIlvVG1tv3yTeBf+k/NF4kF6D6a7abWAoouToWn6RXcrHwyK1jhj7eXgvyrKwJxAY62ZqBX82ywnmJ9jIZDV9y+8hiXxx0X9NfLHTRRCbyisbkNn/79+bpjV0B8JQlVn59sI4hObyC3wA53ixqo6cFr7WQDuddXe8ucEw3qmXOwQsMiJMq9QLkQ4QG5A6Bshs396Lbo06u/rB8a76X7Oc9IJFYvlXrFq5NHbSwSO/Fa05Jnn/tu8/ICbm7IhJYiwnWCcVxXqdNAIC8q+VKd+KAc8Q6lUFRPx2Fi6/UP/LLR6pWB7HRx9U0Ux55/IhR/1tyak0Gr0lOoU0a4qcBHnqBmg3sku2gkOHo3CwHHpO112aLwsbyTZ6SApMPe91+X1GDfBn0o1z/KxnUP3gIJ/MGqGr4HrsewobzREFfvm/LaKQ0HEiLcGHNSwFKs6nATNhk7UnEYg4IwYG7JptzeZ+eO2QtVykBw1Rza2fEZGESGueZAkNp2/lgWM0NHF0zukaxdLsPK/ta01T6+NRj/IxG7i0yzbuVV9999p+SVaRxlzGG51KQEhJqZuYKwTZzI4GwOkymYPe0AQTYRErhFAr1Ll+7OVmxVIfFnYDyIdY2rV/IkCru3z887UzK5cTvkQHMgxUJqkLZMrBvbE=
  bucket: staging.kittycash.io
  skip_cleanup: true
  acl: public-read
  local-dir: build
  on:
    repo: kittycash/kittycash.io
- provider: gcs
  access_key_id: GOOG3UJZKTUH2MM2KWGJ
  secret_access_key:
    secure: tT+pHOM050QGzjBUlDmfvf1pPbbpIlvVG1tv3yTeBf+k/NF4kF6D6a7abWAoouToWn6RXcrHwyK1jhj7eXgvyrKwJxAY62ZqBX82ywnmJ9jIZDV9y+8hiXxx0X9NfLHTRRCbyisbkNn/79+bpjV0B8JQlVn59sI4hObyC3wA53ixqo6cFr7WQDuddXe8ucEw3qmXOwQsMiJMq9QLkQ4QG5A6Bshs396Lbo06u/rB8a76X7Oc9IJFYvlXrFq5NHbSwSO/Fa05Jnn/tu8/ICbm7IhJYiwnWCcVxXqdNAIC8q+VKd+KAc8Q6lUFRPx2Fi6/UP/LLR6pWB7HRx9U0Ux55/IhR/1tyak0Gr0lOoU0a4qcBHnqBmg3sku2gkOHo3CwHHpO112aLwsbyTZ6SApMPe91+X1GDfBn0o1z/KxnUP3gIJ/MGqGr4HrsewobzREFfvm/LaKQ0HEiLcGHNSwFKs6nATNhk7UnEYg4IwYG7JptzeZ+eO2QtVykBw1Rza2fEZGESGueZAkNp2/lgWM0NHF0zukaxdLsPK/ta01T6+NRj/IxG7i0yzbuVV9999p+SVaRxlzGG51KQEhJqZuYKwTZzI4GwOkymYPe0AQTYRErhFAr1Ll+7OVmxVIfFnYDyIdY2rV/IkCru3z887UzK5cTvkQHMgxUJqkLZMrBvbE=
  bucket: kittycash.io
  skip_cleanup: true
  acl: public-read
  local-dir: build
  on:
    tags: true
    repo: kittycash/kittycash.io